// website/sidebars.js
// apiSidebar is generated by `npm run gen-api-docs` — run it before building.

let apiSidebar = [];
try {
  const mod = require('./docs/api-reference/sidebar.ts');
  apiSidebar = mod.default || mod;
} catch {
  // not yet generated
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {type: 'autogenerated', dirName: 'introduction'},
    {type: 'autogenerated', dirName: 'getting-started'},
    {type: 'autogenerated', dirName: 'authentication'},
    {type: 'autogenerated', dirName: 'concepts'},
    ...apiSidebar,
    {type: 'autogenerated', dirName: 'guides'},
  ],
};

module.exports = sidebars;
