// @ts-check

import apiSidebar from './docs/api-reference/sidebar.ts';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {type: 'autogenerated', dirName: 'introduction'},
    {type: 'autogenerated', dirName: 'authentication'},
    {type: 'autogenerated', dirName: 'concepts'},
    // Filters out the auto-generated summary page (replaced by a hand-authored one)
    ...apiSidebar.filter((/** @type {any} */ item) => !(item.type === 'doc' && item.id === 'api-reference/proabono-bo')),
  ],
};

export default sidebars;
